# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0

## Impostare il controllo misto posizione-corrente con Abel, oltre che i limiti di corrente dal wizard ##

shoulder_left_pitch:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
shoulder_left_roll:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
biceps_left:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
elbow_left:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
forearm_left:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
hand_left_1:
  ID: 6
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
hand_left_2:
  ID: 7
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
